<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly
/**
 *   Woo Commerce Page Template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

$body_classes = get_body_class();

if ( in_array( 'archive', $body_classes ) ) {
	$page_type = 'archive_woo';
} else {
	$page_type = 'page';
}

$sb_layout = weaverx_page_lead( $page_type );

// and next the content area.
weaverx_sb_precontent( $page_type );

// generate page content
echo "\n<!-- Weaver Woocommerce page -->\n";
if ( function_exists( 'woocommerce_content' ) ) {
	woocommerce_content();
	if ( $GLOBALS['weaverx_wooshop'] != 0 ) {
		if ( is_shop() ) {
			$url = get_edit_post_link( $GLOBALS['weaverx_wooshop'] );
			if ( $url != '' ) {     // don't show if not there.... (e.g., not admin)
				$before = '<span class="edit-link">';
				$after = '</span>';
				$link_label = esc_html__( 'Edit', 'weaver-xtreme' );
				$link = '<a class="post-edit-link" href="' . $url . '" title="Shop">' . $link_label . '</a>';
				echo $before . $link . $after;
			}
		}
	}
} else {
	while ( have_posts() ) {
		weaverx_post_count_clear();
		the_post();

		get_template_part( 'templates/content', 'page' );

		comments_template( '', true );
	}
	weaverx_edit_link();
}

weaverx_sb_postcontent( $page_type );

weaverx_page_tail( $page_type, $sb_layout );    // end of page wrap


